version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: wang-nginx-dev
    networks:
      - with-nginx
    depends_on:
      - wang
    volumes:
      - ./nginx/wang.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  
  wang:
    # The current dir is the build context
    build:
      context: ./root
      dockerfile: dockerfile.dev
    container_name: wang-dev
    networks:
      with-nginx:
        aliases:
          - wang
      with-mongo:
        aliases:
          - wang
    depends_on:
      - db
    env_file:
      - .env-dev
    volumes:
      - ./root/app:/wang-orthopedics/app

  db:
    image: mongo:latest
    container_name: wang-db-dev
    restart: on-failure
    networks:
      with-mongo:
        aliases:
          - mongo
    volumes:
      - ./mongodata:/data/db


networks:
  with-nginx:
  with-mongo: