version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: wang-nginx
    networks:
      - with-nginx
    depends_on:
      - wang
    volumes:
      - ./nginx/wang.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  
  wang:
    # The current dir is the build context
    build:
      context: ./root
    container_name: wang
    networks:
      with-nginx:
        aliases:
          - wang
      with-mongo:
        aliases:
          - wang
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./root/app:/wang-orthopedics/app

  db:
    image: mongo:latest
    networks:
      with-mongo:
        aliases:
          - mongo



networks:
  with-nginx:
  with-mongo: