FROM python:3.7

ARG rootPath=/wang-orthopedics

WORKDIR ${rootPath}

# Copy the requirements.txt to the upper folder
COPY requirements.txt run.py ./

RUN python3 -m venv env \
  && . env/bin/activate \
  && pip3 install -r requirements.txt

CMD . env/bin/activate && flask run --host 0.0.0.0
