FROM python:3.7

ARG rootPath=/wang-orthopedics

RUN mkdir -p ${rootPath}

WORKDIR ${rootPath}

COPY requirements.txt .

RUN python3 -m venv env \
  && . env/bin/activate \
  && pip3 install -r requirements.txt

CMD . env/bin/activate && gunicorn -w 4 -b 0.0.0.0:5000 "app:create_app()"
